// List
export const FETCH_ALL_LISTS = "FETCH_ALL_LISTS";
export const ADD_NEW_LIST = "ADD_NEW_LIST";
export const ADD_NEW_CARD_TO_LIST = "ADD_NEW_CARD_TO_LIST";
export const DELETE_CARD_FROM_LIST = "DELETE_CARD_FROM_LIST";
export const MOVE_CARD_FROM_LIST = "MOVE_CARD_FROM_LIST";
export const UPDATE_LIST_TITLE = "UPDATE_LIST_TITLE";
export const DELETE_LIST = "DELETE_LIST";

// Quick Editor
export const GET_QUICK_EDITOR_STATE = "GET_QUICK_EDITOR_STATE";
export const TOGGLE_QUICK_EDITOR = "TOGGLE_QUICK_EDITOR";
export const CLOSE_QUICK_EDITOR = "CLOSE_QUICK_EDITOR";
export const UPDATE_CARD_TITLE = "UPDATE_CARD_TITLE";

// Cards
export const SHOW_CARD_MODAL = "SHOW_CARD_MODAL";
export const HIDE_CARD_MODAL = "HIDE_CARD_MODAL";
export const UPDATE_CARD_DESCRIPTION = "UPDATE_CARD_DESCRIPTION";

// Board
export const FETCH_ALL_BOARDS = "FETCH_ALL_BOARDS";
export const ADD_NEW_BOARD = "ADD_NEW_BOARD";
export const SHOW_CREATE_BOARD = "SHOW_CREATE_BOARD";
export const ADD_LIST_TO_BOARD = "ADD_LIST_TO_BOARD";
export const REMOVE_LIST_FROM_BOARD = "REMOVE_LIST_FROM_BOARD";
